### ISSUE TITLE
populate upon save

### ISSUE THREAD

**Issue by sidhansukeshri** [sidhansukeshri/Court-app#5]
populate the database when submit buttom is clicked after altering or updationg the tables in the award and case proceedings page.
deadline is 3 rd feb.

**Comment by SamayMody** [comment]
Can you please give a detailed brief from which collection and which part of the form .And it is the front-end developers task to trigger a scrip upon clicking the submit button so I suggest we assign 1 of our front-end developers with this task of triggering the script I will create in the coming days.

**Comment by sidhansukeshri** [comment]
when the user clicks on the submit buttom after all the modification and updation required to be done in the tables , the table contents need to be updated / feeded in the database . The tables case_award_respondent, case_award_petitioner and case_award_petitioner_ln should get updated in the database with data from the tables Award Details / Proceeding Details, Petitioner Details and Petitioner wise award details on the webpage respectively.

**Comment by sidhansukeshri** [comment]
@SamayMody i have complete the populate upon submit , please try completing the populate upon submiting number type

**Comment by SamayMody** [comment]
Noted ✅️
