### ISSUE TITLE
Details button for awards and case proceedings form.

### ISSUE THREAD

**Issue by AlokChedambath64** [sidhansukeshri/Court-app#6]
Details button should display modal window. 
Deadline: 31/01/24

**Comment by DudeDiv** [comment]
Alok it seems the modal window has already been added to the "Details" button. I saved the HTML code on my system and ran it, I got it exactly as it's supposed to be. I'm attaching the screenshot as reference.
![Screenshot (86)](https://github.com/sidhansukeshri/Court-app/assets/113873506/ad8baf3b-06cc-4cc3-927e-3376ad3ed0df)
![Screenshot (87)](https://github.com/sidhansukeshri/Court-app/assets/113873506/e7cb7324-9735-4543-aa63-bd3328b3bd12)

**Comment by DudeDiv** [comment]
Will do the formatting adjustment by eotd (if required).
