### ISSUE TITLE
details button opens model window

### ISSUE THREAD

**Issue by sidhansukeshri** [sidhansukeshri/Court-app#7]
when the user clicks on the details button the model window should popup as intended , but its not currently . 
try to resolve as soon as possible .

**Comment by DudeDiv** [comment]
Issue resolved. Attached screenshots as to that of the expected output.
![Screenshot (88)](https://github.com/sidhansukeshri/Court-app/assets/113873506/ac397946-0bfb-443c-a197-e33b526b3ba8)
![Screenshot (89)](https://github.com/sidhansukeshri/Court-app/assets/113873506/677cbc53-75f2-4f85-b329-d585d9efc63f)
